services:
  shop-mysql:
    image: registry.cn-shenzhen.aliyuncs.com/hcode/hoj_database
    container_name: shop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database/conf.d:/etc/mysql/conf.d:ro
    networks:
      - shop-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
      interval: 10s

  shop-api:
    image: shop-api
    container_name: shop-api
    restart: unless-stopped
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      API_SERVER_PORT: ${API_SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      # 管理员配置
      ADMIN_USERNAMES: ${ADMIN_USERNAMES:-}
    ports:
      - '3001:3001'
    volumes:
      - ./logs/api:/app/logs
    networks:
      - shop-network
    depends_on:
      shop-mysql:
        condition: service_healthy

  shop-nginx:
    image: nginx:alpine
    container_name: shop-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/ssl/private:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - shop-network
    depends_on:
      - shop-api

  shop-redis:
    image: redis:7-alpine
    container_name: shop-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - shop-network
    command: redis-server --appendonly yes

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  shop-network:
    driver: bridge
